config/routes.rb
Rails.application.routes.draw do
  get 'claims/list' => 'claims#list' 
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'statics#top'
  resources :claims do
    resources :likes, only: [:create, :destroy]
    resources :questions, only: [:create]
  end
  resources :users, only: [:show]
  resources :parent_children, only: [:create, :destroy]
  
end

app/models/claim.rb
class Claim < ApplicationRecord

    belongs_to :user

    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user

    has_many :questions, dependent: :destroy

end

app/controllers/claims_controller.rb
class ClaimsController < ApplicationController
    
    before_action :authenticate_user!
    def index
        @claims = Claim.all
    end

    def new
        @claim = Claim.new
    end
    def create
        claim = Claim.new(claim_params)
        claim.user_id = current_user.id
        if claim.save
            redirect_to :action => "index"
        else
            redirect_to :action => "new"
        end
    end
    
    def show
        @claim = Claim.find(params[:id])

        @parent_claims = Claim.where(id:@claim.parent_id)
        @child_claims = Claim.where(parent_id:@claim.parent_id)
        

        @question = Question.new
        @questions = @claim.questions

        @child_claim = Claim.new

    end

    def edit
        @claim = Claim.find(params[:id])
    end

    def update
        claim = Claim.find(params[:id])
        if claim.update(claim_params)
            redirect_to :action => "show", :id => claim.id
        else
            redirect_to :action => "new"
        end
    end

    def destroy
        claim = Claim.find(params[:id])
        claim.destroy
        redirect_to action: :index
    end

    def list
        data = {
            "nodes": [
                {"id": "Myriel", "group": 1},
                {"id": "Napoleon", "group": 1},
                {"id": "Mlle.Baptistine", "group": 1},
                {"id": "Mme.Magloire", "group": 1},
                {"id": "CountessdeLo", "group": 1},
                {"id": "Geborand", "group": 1},
                {"id": "Champtercier", "group": 1},
                {"id": "Cravatte", "group": 1},
                # {"id": "Count", "group": 1},
                # {"id": "OldMan", "group": 1},
                # {"id": "Labarre", "group": 2},
                # {"id": "Valjean", "group": 2},
                # {"id": "Marguerite", "group": 3},
                # {"id": "Mme.deR", "group": 2},
                # {"id": "Isabeau", "group": 2},
                # {"id": "Gervais", "group": 2},
                # {"id": "Tholomyes", "group": 3},
                # {"id": "Listolier", "group": 3},
                # {"id": "Fameuil", "group": 3},
                # {"id": "Blacheville", "group": 3},
                # {"id": "Favourite", "group": 3},
                # {"id": "Dahlia", "group": 3},
                # {"id": "Zephine", "group": 3},
                # {"id": "Fantine", "group": 3},
                # {"id": "Mme.Thenardier", "group": 4},
                # {"id": "Thenardier", "group": 4},
                # {"id": "Cosette", "group": 5},
                # {"id": "Javert", "group": 4},
                # {"id": "Fauchelevent", "group": 0},
                # {"id": "Bamatabois", "group": 2},
                # {"id": "Perpetue", "group": 3},
                # {"id": "Simplice", "group": 2},
                # {"id": "Scaufflaire", "group": 2},
                # {"id": "Woman1", "group": 2},
                # {"id": "Judge", "group": 2},
                # {"id": "Champmathieu", "group": 2},
                # {"id": "Brevet", "group": 2},
                # {"id": "Chenildieu", "group": 2},
                # {"id": "Cochepaille", "group": 2},
                # {"id": "Pontmercy", "group": 4},
                # {"id": "Boulatruelle", "group": 6},
                # {"id": "Eponine", "group": 4},
                # {"id": "Anzelma", "group": 4},
                # {"id": "Woman2", "group": 5},
                # {"id": "MotherInnocent", "group": 0},
                # {"id": "Gribier", "group": 0},
                # {"id": "Jondrette", "group": 7},
                # {"id": "Mme.Burgon", "group": 7},
                # {"id": "Gavroche", "group": 8},
                # {"id": "Gillenormand", "group": 5},
                # {"id": "Magnon", "group": 5},
                # {"id": "Mlle.Gillenormand", "group": 5},
                # {"id": "Mme.Pontmercy", "group": 5},
                # {"id": "Mlle.Vaubois", "group": 5},
                # {"id": "Lt.Gillenormand", "group": 5},
                # {"id": "Marius", "group": 8},
                # {"id": "BaronessT", "group": 5},
                # {"id": "Mabeuf", "group": 8},
                # {"id": "Enjolras", "group": 8},
                # {"id": "Combeferre", "group": 8},
                # {"id": "Prouvaire", "group": 8},
                # {"id": "Feuilly", "group": 8},
                # {"id": "Courfeyrac", "group": 8},
                # {"id": "Bahorel", "group": 8},
                # {"id": "Bossuet", "group": 8},
                # {"id": "Joly", "group": 8},
                # {"id": "Grantaire", "group": 8},
                # {"id": "MotherPlutarch", "group": 9},
                # {"id": "Gueulemer", "group": 4},
                # {"id": "Babet", "group": 4},
                # {"id": "Claquesous", "group": 4},
                # {"id": "Montparnasse", "group": 4},
                # {"id": "Toussaint", "group": 5},
                # {"id": "Child1", "group": 10},
                # {"id": "Child2", "group": 10},
                # {"id": "Brujon", "group": 4},
                # {"id": "Mme.Hucheloup", "group": 8}
            ],
            "links": [
                {"source": "Napoleon", "target": "Myriel", "value": 1},
                # {"source": "Mlle.Baptistine", "target": "Myriel", "value": 8},
                # {"source": "Mme.Magloire", "target": "Myriel", "value": 10},
                # {"source": "Mme.Magloire", "target": "Mlle.Baptistine", "value": 6},
                # {"source": "CountessdeLo", "target": "Myriel", "value": 1},
                # {"source": "Geborand", "target": "Myriel", "value": 1},
                # {"source": "Champtercier", "target": "Myriel", "value": 1},
                # {"source": "Cravatte", "target": "Myriel", "value": 1},
                # {"source": "Count", "target": "Myriel", "value": 2},
                # {"source": "OldMan", "target": "Myriel", "value": 1},
                # {"source": "Valjean", "target": "Labarre", "value": 1},
                # {"source": "Valjean", "target": "Mme.Magloire", "value": 3},
                # {"source": "Valjean", "target": "Mlle.Baptistine", "value": 3},
                # {"source": "Valjean", "target": "Myriel", "value": 5},
                # {"source": "Marguerite", "target": "Valjean", "value": 1},
                # {"source": "Mme.deR", "target": "Valjean", "value": 1},
                # {"source": "Isabeau", "target": "Valjean", "value": 1},
                # {"source": "Gervais", "target": "Valjean", "value": 1},
                # {"source": "Listolier", "target": "Tholomyes", "value": 4},
                # {"source": "Fameuil", "target": "Tholomyes", "value": 4},
                # {"source": "Fameuil", "target": "Listolier", "value": 4},
                # {"source": "Blacheville", "target": "Tholomyes", "value": 4},
                # {"source": "Blacheville", "target": "Listolier", "value": 4},
                # {"source": "Blacheville", "target": "Fameuil", "value": 4},
                # {"source": "Favourite", "target": "Tholomyes", "value": 3},
                # {"source": "Favourite", "target": "Listolier", "value": 3},
                # {"source": "Favourite", "target": "Fameuil", "value": 3},
                # {"source": "Favourite", "target": "Blacheville", "value": 4},
                # {"source": "Dahlia", "target": "Tholomyes", "value": 3},
                # {"source": "Dahlia", "target": "Listolier", "value": 3},
                # {"source": "Dahlia", "target": "Fameuil", "value": 3},
                # {"source": "Dahlia", "target": "Blacheville", "value": 3},
                # {"source": "Dahlia", "target": "Favourite", "value": 5},
                # {"source": "Zephine", "target": "Tholomyes", "value": 3},
                # {"source": "Zephine", "target": "Listolier", "value": 3},
                # {"source": "Zephine", "target": "Fameuil", "value": 3},
                # {"source": "Zephine", "target": "Blacheville", "value": 3},
                # {"source": "Zephine", "target": "Favourite", "value": 4},
                # {"source": "Zephine", "target": "Dahlia", "value": 4},
                # {"source": "Fantine", "target": "Tholomyes", "value": 3},
                # {"source": "Fantine", "target": "Listolier", "value": 3},
                # {"source": "Fantine", "target": "Fameuil", "value": 3},
                # {"source": "Fantine", "target": "Blacheville", "value": 3},
                # {"source": "Fantine", "target": "Favourite", "value": 4},
                # {"source": "Fantine", "target": "Dahlia", "value": 4},
                # {"source": "Fantine", "target": "Zephine", "value": 4},
                # {"source": "Fantine", "target": "Marguerite", "value": 2},
                # {"source": "Fantine", "target": "Valjean", "value": 9},
                # {"source": "Mme.Thenardier", "target": "Fantine", "value": 2},
                # {"source": "Mme.Thenardier", "target": "Valjean", "value": 7},
                # {"source": "Thenardier", "target": "Mme.Thenardier", "value": 13},
                # {"source": "Thenardier", "target": "Fantine", "value": 1},
                # {"source": "Thenardier", "target": "Valjean", "value": 12},
                # {"source": "Cosette", "target": "Mme.Thenardier", "value": 4},
                # {"source": "Cosette", "target": "Valjean", "value": 31},
                # {"source": "Cosette", "target": "Tholomyes", "value": 1},
                # {"source": "Cosette", "target": "Thenardier", "value": 1},
                # {"source": "Javert", "target": "Valjean", "value": 17},
                # {"source": "Javert", "target": "Fantine", "value": 5},
                # {"source": "Javert", "target": "Thenardier", "value": 5},
                # {"source": "Javert", "target": "Mme.Thenardier", "value": 1},
                # {"source": "Javert", "target": "Cosette", "value": 1},
                # {"source": "Fauchelevent", "target": "Valjean", "value": 8},

app/helpers/claims_helper.rb
module ClaimsHelper
end

app/views/claims/edit.html.erb
<%= form_for @claim do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, :size => 140 %> 
  <%= f.submit "編集する" %>
<% end %>

app/views/claims/index.html.erb
<%= link_to "新規投稿ページへ", new_claim_path %>

<h3>一覧</h3>
<div class="claims-container">
    <% @claims.each do |t| %>
    <div class="claim">
        <%= t.title %>
        <% if user_signed_in? %>
            <% if current_user.already_liked?(t) %>
                <%= link_to claim_like_path(id: t.id, claim_id: t.id), method: :delete do %>
                    <i class="fas fa-heart"></i><%= t.likes.count %>
                <% end %>
            <% else %>
                <%= link_to claim_likes_path(claim_id: t.id), method: :post  do %>
                    <i class="far fa-heart"></i><%= t.likes.count %>
                <% end %>
            <% end %>
        <% else %>
            <i class="far fa-heart"></i><%= t.likes.count %>
        <% end %>
            <%= t.created_at %>
            <a href="/users/<%= t.user.id %>"><%= t.user.name %></a>
            <%= link_to "詳細へ", claim_path(t.id) %>
        <% if user_signed_in? && current_user.id == t.user_id %>  
            <%= link_to "編集する", edit_claim_path(t.id) %>
        <% end %> 
    </div>
    <% end %>
    <%= button_to 'ログアウト', destroy_user_session_path, method: :delete %>
    <% if user_signed_in? %>
        <%= link_to "マイページへ", user_path(current_user.id) %>　
<%= link_to "一覧に戻る", claims_path %>

    <% end %>
</div>

app/views/claims/new.html.erb
<h3>新規投稿</h3>
<%= form_for @claim do |f| %>
    <div class="field">
        <%= f.label :title %>
        <%= f.text_field :title, :size => 140 %>
    </div>
    <%= f.submit "投稿する" %>
<% end %>
<%= link_to "投稿一覧に戻る", claims_path %>

app/views/claims/show.html.erb
<!DOCTYPE html>
<h3>詳細</h3>

<div class="parent_claim">
<h4>親投稿</h4>
<% @parent_claims.each do |t| %>
    <%= t.title %>
    <% if user_signed_in? %>
        <% if current_user.already_liked?(t) %>
            <%= link_to claim_like_path(id: t.id, claim_id: t.id), method: :delete do %>
                <i class="fas fa-heart"></i><%= t.likes.count %>
            <% end %>
        <% else %>
            <%= link_to claim_likes_path(claim_id: t.id), method: :post do %>
                <i class="far fa-heart"></i><%= t.likes.count %>
            <% end %>
        <% end %>
    <% else %>
        <i class="far fa-heart"></i><%= t.likes.count %>
    <% end %>
        <%= t.created_at %>
        <a href="/users/<%= t.user.id %>"><%= t.user.name %></a>
        <%= link_to "詳細へ", claim_path(t.id) %>
    <% if user_signed_in? && current_user.id == t.user_id %>  
        <%= link_to "編集する", edit_claim_path(t.id) %>
    <% end %>
    <br>
<% end %>
</div> 


<div class="claim">
<h4>投稿</h4>
    <p><%= @claim.title %></p>
    <p><%= @claim.created_at %></p>

    <% if user_signed_in? %>
    <% if current_user.already_liked?(@claim) %>
        <%= link_to claim_like_path(@claim), method: :delete do %>
            <i class="fas fa-heart"></i><%= @claim.likes.count %>
        <% end %>
    <% else %>
        <%= link_to claim_likes_path(@claim), method: :post do %>
            <i class="far fa-heart"></i><%= @claim.likes.count %>
        <% end %>
    <% end %>
<% else %>
    <i class="far fa-heart"></i><%= @claim.likes.count %>
<% end %>
<% if user_signed_in? && current_user.id == @claim.user_id %> 
    <%= link_to "削除する", claim_path(@claim.id), method: :delete %>
    <%= link_to "編集する", edit_claim_path(@claim.id) %>
<% end %>
</div>

<div class="questions">
    <h4>質問一覧</h4>
    <% @questions.each do |c| %>
    <div>
        <%= c.content %>
        <%= c.user.name %>
    </div>
        <br>
    <% end %>
</div>    
<div class="questions">
    <h4>反論一覧</h4>
    <% @child_claims.each do |d| %>
    <div>
        <%= d.title %>
        <%= d.user.name %>
    </div>
        <br>
    <% end %>
</div>   

<div class= "child_claim_form">
    <% if user_signed_in? %>
        <%= form_for @child_claim do |f| %>
            <%= f.text_area :title %>
            <%= f.hidden_field :parent_id, :value => @claim.id%>
            <%= button_tag type: "submit" do %>
                <i class="far fa-comments"></i> 反論投稿する
            <% end %>
        <% end %>
    <% end %>
</div>

<div class= "question_form">
    <% if user_signed_in? %>
        <%= form_with(model: [@claim, @question], local: true) do |f| %>
            <%= f.text_area :content %>
            <%= button_tag type: "submit" do %>
                <i class="far fa-comments"></i> 質問する
            <% end %>
        <% end %>
    <% end %>   
</div>

<%= link_to "一覧に戻る", claims_path %>
<h1>こっからテスト</h1>


<meta charset="utf-8">

<style>
    .links line {
        stroke: #555;
        stroke-opacity: 1;
    }
    .nodes circle, .nodes rect {
        stroke: #fff;
        stroke-width: 1.5px;
    }
    .nodes rect {
        stroke-width: 1.0px;
    }
</style>

<svg width="1200" height="600"></svg>

<%# 「views/layouts/application.html.erb」で読み込むように変更 %>
<%# <script src="https://d3js.org/d3.v7.min.js"></script> %>

<script>
    var svg = d3.select("svg"),
        width = +svg.attr("width"),
        height = +svg.attr("height");

    var color = d3.scaleOrdinal(d3.schemeCategory10);

    var simulation = d3.forceSimulation()
        .force("collide",d3.forceCollide().radius(35).iterations(16) ) //衝突値の設定
        .force("link", d3.forceLink().id(function(d) { return d.id; }))
        .force("charge", d3.forceManyBody().strength(-250))
        .force("center", d3.forceCenter(width / 2, height / 2))
        .force("x", d3.forceX().x(width / 2).strength(0.2))  //x方向に戻る力
        .force("y", d3.forceY().y(height / 2).strength(0.1))  //y方向に戻る力;

    var g = svg.append("g");

// d3.json("<%= asset_path 'miserables.json' %>").then(function(graph) {
    d3.json("list").then(function(graph) {
        // if (error) throw error;

        var link = g.append("g")
            .attr("class", "links zoom")
            .selectAll("line")
            .data(graph.links)
            .enter().append("line")
            .attr("stroke-width", function(d) { return Math.sqrt(d.value); });

        // var node = svg.append("g")
        //     .attr("class", "nodes")
        //     .selectAll("circle")
        //     .data(graph.nodes)
        //     .enter().append("circle")
        //     .attr("r", 5)
        //     .attr("fill", function(d) { return color(d.group); })
        //     .call(d3.drag()
        //         .on("start", dragstarted)
        //         .on("drag", dragged)
        //         .on("end", dragended));

        var nodebase = g.append("g");
        var node = nodebase
            .attr("class", "nodes zoom")
            .selectAll("rect")
            .data(graph.nodes)
            .enter().append("rect")
            .attr("width", 60)
            .attr("height", 20)
            .attr("rx", 5)
            .attr("ry", 5)
            .attr("fill", function(d) { return color(d.group); })
            .call(d3.drag()
                .on("start", dragstarted)
                .on("drag", dragged)
                .on("end", dragended));

        node.append("title")
            .text(function(d) { return d.id; });

        var nodetext = nodebase
            .selectAll("text")
            .data(graph.nodes)
            .enter()
            .append("text")
            .attr("font-size", "10px")
            .attr("dx", 2)
            .attr("dy", 2)
            .text('こめんと')
            .call(d3.drag()
                .on("start", dragstarted)
                .on("drag", dragged)
                .on("end", dragended));

        simulation
            .nodes(graph.nodes)
            .on("tick", ticked);

        simulation.force("link")
            .links(graph.links);

        function ticked() {
            link
                .attr("x1", function(d) { return d.source.x; })
                .attr("y1", function(d) { return d.source.y; })
                .attr("x2", function(d) { return d.target.x; })
                .attr("y2", function(d) { return d.target.y; });

            node
                .attr("x", function(d) { return d.x - 30; })
                .attr("y", function(d) { return d.y - 10; });

            nodetext
                .attr("x", function(d) { return d.x - 30; })
                .attr("y", function(d) { return d.y - 10 + 10; });
        }
    });

    // zoom対応
    var zoom = d3.zoom()
        .scaleExtent([1, 8])
        .on('zoom', function(event) {
            g.selectAll('.zoom')
            .attr('transform', event.transform);
    });

    svg.call(zoom);

    function dragstarted(event) {
        if (!event.active) simulation.alphaTarget(0.3).restart();
        event.subject.fx = event.subject.x;
        event.subject.fy = event.subject.y;
    }

    function dragged(event) {
        event.subject.fx = event.x;
        event.subject.fy = event.y;
    }

    function dragended(event) {
        if (!event.active) simulation.alphaTarget(0);
        event.subject.fx = null;
        event.subject.fy = null;
    }
</script>